[package]
name = "bkm"
version = "0.1.0"
authors = ["Natsuki Tanaka <n2kia4@gmail.com>"]

[dependencies]
clap = "2.32.0"
dirs = "1.0.4"
reqwest = "0.9.2"
rusqlite = "0.14.0"
select = "0.4.2"
webbrowser = "0.3.1"
